### ISSUE TITLE
Beast Ball support

### ISSUE THREAD

**Issue by drgoku282** [TheIronDeveloper/pokemon-wondertrade-analytics#25]
Hello, I wanted to register some wonder trades, but I checked through the site and couldn't find an option to add pokémon in a Beast Ball. Can you add Beast Ball to the ball list?

**Comment by TheIronDeveloper** [comment]
Hey, sorry for the late reply.  I will add support for it tonight when I get back from work 👍

**Comment by TheIronDeveloper** [comment]
Alright, I added in beastball to the list, thanks for catching that!
